apiVersion: v1
kind: Service
metadata:
  name: task
spec:
  type: NodePort
  selector:
    app: task
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081